name: Draft Tagged Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/tests.yaml

  release:
    name: Build and Draft Release
    runs-on: ubuntu-24.04
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Get version from pyproject.toml
        id: version
        run: echo "version=$(poetry version -s)" >> "$GITHUB_OUTPUT"

      - name: Validate tag matches pyproject.toml version
        run: |
          tag_version=${GITHUB_REF_NAME#v}
          file_version=$(poetry version -s)
          echo "Tag: $tag_version | File: $file_version"
          if [ "$tag_version" != "$file_version" ]; then
            echo "❌ Version mismatch"
            exit 1
          fi

      - name: Check version is newer than PyPI
        run: |
          package="charmed-analytics-ci"
          tag_version=${GITHUB_REF_NAME#v}

          latest=$(curl -s https://pypi.org/pypi/$package/json | jq -r '.releases | keys[]' | sort -V | tail -1)

          echo "Latest on PyPI: $latest"
          echo "Git tag: $tag_version"

          if [ "$tag_version" = "$latest" ]; then
            echo "❌ Version $tag_version already exists on PyPI"
            exit 1
          fi

      - name: Build package
        run: poetry build

      - name: Create Draft GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: |
            dist/*.whl
            dist/*.tar.gz
