name: On Pull Request

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yaml
    secrets:
      CHACI_TEST_TOKEN: ${{ secrets.CHACI_TEST_TOKEN }}
      CHACI_GPG_PRIVATE: ${{ secrets.CHACI_GPG_PRIVATE }}
      CHACI_GPG_PASSPHRASE: ${{ secrets.CHACI_GPG_PASSPHRASE }}
