name: Tests

on:
  workflow_call:
    secrets:
      CHACI_TEST_TOKEN:
        required: true
      CHACI_GPG_PRIVATE:
        required: true
      CHACI_GPG_PASSPHRASE:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: pipx install tox
      - name: Run linters
        run: tox -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: pipx install tox
      - name: Run tests
        run: tox -e unit

  integration:
    name: Integration tests (microk8s)
    runs-on: ubuntu-24.04
    env:
      CHACI_TEST_TOKEN: ${{ secrets.CHACI_TEST_TOKEN }}
      CHACI_TEST_REPO: canonical/test-kubeflow-automation
      CHACI_TEST_BASE_BRANCH: test-rocks-automation
      CHACI_TEST_EMAIL: kubeflow-admin@lists.canonical.com
      GPG_TTY: /dev/tty

    steps:
      - uses: actions/checkout@v4

      - run: pipx install tox

      - name: Run integration tests (with GPG setup)
        run: |
          # Setup GPG for signing
          echo "${{ secrets.CHACI_GPG_PRIVATE }}" | gpg --batch --import

          KEY_ID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/ {print $5; exit}')
          echo "Using GPG key: $KEY_ID"

          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg

          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo RELOADAGENT | gpg-connect-agent

          echo "${{ secrets.CHACI_GPG_PASSPHRASE }}" | \
            gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 \
            --export-secret-keys "$KEY_ID" > /dev/null

          git config --global user.name "Kubeflow Admin"
          git config --global user.email "kubeflow-admin@lists.canonical.com"
          git config --global user.signingkey "$KEY_ID"
          git config --global commit.gpgsign true

          # Run the integration tests (commits will be signed if needed)
          tox -vve integration
