name: Tests

on:
  workflow_call:
    secrets:
      CHACI_TEST_TOKEN:
        required: true
      CHACI_GPG_PRIVATE:
        required: true
      CHACI_GPG_PASSPHRASE:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: pipx install tox
      - name: Run linters
        run: tox -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: pipx install tox
      - name: Run tests
        run: tox -e unit

  integration:
    name: Integration tests (microk8s)
    runs-on: ubuntu-24.04
    env:
      CHACI_TEST_TOKEN: ${{ secrets.CHACI_TEST_TOKEN }}
      CHACI_TEST_REPO: canonical/test-kubeflow-automation
      CHACI_TEST_BASE_BRANCH: test-rocks-automation
      CHACI_TEST_EMAIL: kubeflow-admin@lists.canonical.com
    steps:
      - uses: actions/checkout@v4

      - name: Install gpg-preset-passphrase and configure GPG
        run: |
          sudo install -m 755 -o root -g root /usr/lib/gnupg2/gpg-preset-passphrase /usr/bin/

          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg

          echo "$CHACI_GPG_PRIVATE" | gpg --batch --import

          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo RELOADAGENT | gpg-connect-agent

          export GPG_TTY=$(tty || echo not-a-tty)
          KEYGRIP=$(gpg --with-keygrip --list-secret-keys | awk '/Keygrip/ { print $2; exit }')

          # Load passphrase into agent
          echo "$CHACI_GPG_PASSPHRASE" | /usr/bin/gpg-preset-passphrase --preset "$KEYGRIP"

          KEY_ID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/ { print $5; exit }')
          echo -e "trust\n5\ny\nsave\n" | gpg --batch --yes --pinentry-mode loopback --command-fd 0 --edit-key "$KEY_ID"

          git config --global user.name "Canonical CI Bot"
          git config --global user.email "$CHACI_TEST_EMAIL"
          git config --global user.signingkey "$KEY_ID"
          git config --global commit.gpgsign true
          git config --global gpg.program gpg
        env:
          CHACI_GPG_PRIVATE: ${{ secrets.CHACI_GPG_PRIVATE }}
          CHACI_GPG_PASSPHRASE: ${{ secrets.CHACI_GPG_PASSPHRASE }}
          CHACI_TEST_EMAIL: ${{ env.CHACI_TEST_EMAIL }}

      - run: pipx install tox

      - name: Run integration tests
        run: tox -vve integration
