name: Tests

on:
  workflow_call:
    secrets:
      CHACI_TEST_TOKEN:
        required: true
      CHACI_GPG_PRIVATE:
        required: true
      CHACI_GPG_PASSPHRASE:
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: pipx install tox
      - name: Run linters
        run: tox -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: pipx install tox
      - name: Run tests
        run: tox -e unit

  integration:
    name: Integration tests (microk8s)
    runs-on: ubuntu-24.04
    env:
      CHACI_TEST_TOKEN: ${{ secrets.CHACI_TEST_TOKEN }}
      CHACI_TEST_REPO: canonical/test-kubeflow-automation
      CHACI_TEST_BASE_BRANCH: test-rocks-automation
      CHACI_TEST_EMAIL: kubeflow-admin@lists.canonical.com
    steps:
      - uses: actions/checkout@v4

      - name: Import and configure the GPG key
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg

          echo "$CHACI_GPG_PRIVATE" | gpg --batch --import

          # Force loopback pinentry mode
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo RELOADAGENT | gpg-connect-agent

          export GPG_TTY=$(tty || echo not-a-tty)
          export GPG_PASS="$CHACI_GPG_PASSPHRASE"

          # Get key ID
          KEY_ID=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/ { print $5; exit }')

          # Trust the key non-interactively
          echo -e "trust\n5\ny\nsave\n" | \
            gpg --batch --yes --pinentry-mode loopback \
                --passphrase "$GPG_PASS" \
                --command-fd 0 --edit-key "$KEY_ID"

          # Git config for signed commits
          git config --global user.name "ckfbot"
          git config --global user.email "$CHACI_TEST_EMAIL"
          git config --global user.signingkey "$KEY_ID"
          git config --global commit.gpgsign true
          git config --global gpg.program gpg

        env:
          CHACI_GPG_PRIVATE: ${{ secrets.CHACI_GPG_PRIVATE }}
          CHACI_GPG_PASSPHRASE: ${{ secrets.CHACI_GPG_PASSPHRASE }}
          CHACI_TEST_EMAIL: ${{ env.CHACI_TEST_EMAIL }}

      - run: pipx install tox

      - name: Run integration tests
        run: tox -vve integration
